name: CI

on:
  push:
    branches: [ main ]
    
env:
  BUCKET: followx.com.br
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn install
        
      #- name: Build
        #run: yarn build
        
      - name: Execute Server API
        run: yarn start ./server/server.js
        
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJETO }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Upload Files to Bucket
        run: gsutil -m rsync ./build gs://"$BUCKET"
        
      - name: Allow public access
        run: gsutil acl ch -u AllUsers:O gs://"$BUCKET"
