name: CI

on:
  push:
    branches: [ main ]
    
env:
  BUCKET: cwvdigital.com.br
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm build
        
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJETO }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Upload Files to Bucket
        run: gsutil -m rsync -R ./build gs://"$BUCKET"
        
      - name: Allow public access
        run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"

      # Set cache meta for static files
      - name: Set Cache-Control
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}
        
      # Set cache meta for index.html
      - name: Set Cache-Control
        run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
